version: "3.9"
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: money_box
      POSTGRES_USER: money_box
      POSTGRES_PASSWORD: money_box
    expose:
      - 5432
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./tirelire:/app/tirelire