# Generated by Django 4.2 on 2023-04-05 17:24

from decimal import Decimal

from django.db import migrations

EUR_CASH_DATA = [
    ('bill', Decimal('200')),
    ('bill', Decimal('100')),
    ('bill', Decimal('50')),
    ('bill', Decimal('20')),
    ('bill', Decimal('10')),
    ('bill', Decimal('5')),
    ('coin', Decimal('2')),
    ('coin', Decimal('1')),
    ('coin', Decimal('0.5')),
    ('coin', Decimal('0.2')),
    ('coin', Decimal('0.1')),
    ('coin', Decimal('0.05')),
    ('coin', Decimal('0.02')),
    ('coin', Decimal('0.01')),
]


def add_eur_cash_data(apps, schema_editor):
    Cash = apps.get_model('app', 'Cash')
    cash_data = []
    for cash_type, value in EUR_CASH_DATA:
        cash_data.append(Cash(cash_type=cash_type, value=value))
    Cash.objects.bulk_create(cash_data)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_eur_cash_data),
    ]
